#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 14 20:03:27 2017

@author: bedinghausa
"""
print("Please think of a number between 0 and 100!")
h = 100
l = 0

gu = (h - l) // 2
print("Is your secret number " + str(gu) + '?')
a = input(str("Enter 'h' to indicate the guess is too high. Enter 'l' to indicate the guess is too low. Enter 'c' to indicate I guessed correctly."))
if a == "l":
    l = gu
elif a == 'h':
    h = gu
elif a == 'c': 
    print("Game over. Your secret number was: " + str(gu))
else:
    print("Sorry, I did not understand your input.")
    

